#!/bin/bash

set -e

dir=$(dirname "$0")
source "$dir"/sm-helper-functions

uname -a
cat /etc/issue || :
cat /etc/os-release || :

# Smoke test - Python version
python3 --version

echo "sm-local-configure: Installing tools. The 'sudo' commands can ask for your password."

_install_unzip
_install_curl
_install_aws_cli

echo "AWS default region - $AWS_DEFAULT_REGION"
echo "AWS region - $AWS_REGION"
aws configure list

_install_session_manager_plugin