#!/bin/bash

# Commands:
# connect <notebook-instance-name>
# run-command <command> <args...>

COMMAND=$1

if [[ "$COMMAND" == "connect" ]]; then

  NOTEBOOK_INSTANCE_NAME="$2"

  INSTANCE_ID=$(python <<EOF
import sagemaker; from sagemaker_ssh_helper.manager import SSMManager;
import logging; logging.basicConfig(level=logging.INFO);
print(SSMManager().get_notebook_instance_ids("$NOTEBOOK_INSTANCE_NAME", timeout_in_sec=300)[0])
EOF
  )

  sm-local-start-ssh "$INSTANCE_ID" \
      -L localhost:17022:localhost:22

elif [[ "$COMMAND" == "run-command" ]]; then

  shift
  ARGS=$*

  # shellcheck disable=SC2086
  ssh -i ~/.ssh/sagemaker-ssh-gw -p 10022 root@localhost \
    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    $ARGS

else
    echo "Unknown command: $COMMAND"
fi