#!/bin/bash

# When a user logs in with SSH or remote interpreter, we want env vars to be the same as set by SageMaker

set -e

export START_SSH=false
env | grep -E -v "^(HOME=|USER=|MAIL=|LC_ALL=|LS_COLORS=|LANG=|HOSTNAME=|PWD=|TERM=|SHLVL=|LANGUAGE=|_=)" \
  > /etc/environment
cat /etc/environment

# FIXME: needs quoting of spaces, newlines and other special characters like other quotes
# E.g., 'apt-get install stress' doesn't work correctly:
# /usr/sbin/update-info-dir: 13: /etc/environment: cannot open 419: No such file
# NVIDIA_REQUIRE_CUDA=cuda>=11.1 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=450,driver<451
